apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gitops-and-k8s-cluster
  region: us-west-2
  version: 1.19

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 4
    ssh: # import public key from file
      publicKeyName: stang-linux-us-west-2

  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 4
    ssh: # import public key from file
      publicKeyName: stang-linux-us-west-2

cloudWatch:
    clusterLogging:
        # enable specific types of cluster control plane logs
        enableTypes: ["all"]